Repository team-peekabook/Peekabook-Gidi, pull requests merged in 2023-01, with the labels that each got.

#15 Feature/수빈
  README.md
  석식 이슈.md
Labels: 수빈

#10 Update README.md
  README.md
Labels: 태영

#8 Update README.md
  README.md
Labels: good first issue, help wanted, 수빈, 현우

#19 Update README.md
  README.md
Labels: enhancement, 수빈

#22 Update README.md
  README.md
Labels: 수빈

#24 Update README.md
  README.md
Labels: 🥦 지우

#26 Update README.md
  README.md
Labels: duplicate, 수빈

#30 Create ziwooZZANG
  ziwooZZANG
Labels: enhancement, 🥦 지우

#32 Update README.md
  README.md
Labels: 수빈
